#pragma once

#include <MFrame/IWindow.h>
#include <MFrame/MAppCreateWindow.h>
#include <MFrame/MAppData.h>
#include <MFrame/MAppDataUnit.h>
#include <MFrame/MAppEvent.h>
#include <MFrame/MAppFrameData.h>
#include <MFrame/MAppWindow.h>
#include <MFrame/MAppUI.h>
#include <MFrame/MAppFrameUI.h>
#include <MFrame/MAppInfoWindow.h>
#include <MFrame/MAppInstance.h>
#include <MFrame/MAppManager.h>
#include <MFrame/MAppPlugins.h>
#include <MFrame/MAppStartPage.h>
#include <MFrame/MStream.h>
#include <MFrame/MBeamWindow.h>
#include <MFrame/MFrameWindow.h>
#include <MFrame/MHostroyProjectInfo.h>
#include <MFrame/MAsioComInstance.h>
#include <MFrame/MMainWindow.h>
#include <MFrame/MFrameWindow.h>
#include <MFrame/MMenuAction.h>
#include <MFrame/MMenuBar.h>
#include <MFrame/MTreeModule.h>
#include <MFrame/MProjectInfoWindow.h>
#include <MFrame/MNewProjectWindow.h>
